Added Image Labels Verification

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -186,3 +186,16 @@ jobs:
           docker pull quay.io/${{ env.IMAGE_NAME }}:latest
           docker manifest inspect quay.io/${{ env.IMAGE_NAME }}:latest | jq '.manifests[] | select(.platform.architecture == "amd64" or .platform.architecture == "arm64" or .platform.architecture == "s390x" or .platform.architecture == "ppc64le")'
 
+      - name: Verify Image Labels
+        run: |
+          LABELS=$(docker inspect quay.io/${{ env.IMAGE_NAME }}:latest | jq '.[].Config.Labels')
+          echo "Labels: $LABELS"
+          # Check for specific labels
+          if [[ "$LABELS" == *"version=${{ env.VERSION }}"* && \
+                "$LABELS" == *"build-date=${{ env.BUILD_DATE }}"* && \
+                "$LABELS" == *"architecture=${{ env.ARCHITECTURE }}"* ]]; then
+            echo "All labels are correctly set."
+          else
+            echo "Some labels are missing or incorrect."
+            exit 1
+          fi
